import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/home/NavBar";

const ibm = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ar" dir="rtl" className={`${ibm.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <header className="border-b border-b-[#C3C6D7]">
          <NavBar />
        </header>
        {children}
      </body>
    </html>
  );
}
